In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression ## for performing the logistic Regression
from sklearn.metrics import accuracy_score ## to obtain the accuracy score
import pandas as pd


In [2]:
%pwd

'C:\\Users\\Abhi\\Desktop'

In [4]:
%cd C:\\Users\\Abhi\\Desktop\\Machine learning

C:\Users\Abhi\Desktop\Machine learning


In [6]:
white=pd.read_csv("wine.csv", sep=",")
white

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.0             0.270         0.36           20.70      0.045   
1               6.3             0.300         0.34            1.60      0.049   
2               8.1             0.280         0.40            6.90      0.050   
3               7.2             0.230         0.32            8.50      0.058   
4               7.2             0.230         0.32            8.50      0.058   
5               8.1             0.280         0.40            6.90      0.050   
6               6.2             0.320         0.16            7.00      0.045   
7               7.0             0.270         0.36           20.70      0.045   
8               6.3             0.300         0.34            1.60      0.049   
9               8.1             0.220         0.43            1.50      0.044   
10              8.1             0.270         0.41            1.45      0.033   
11              8.6             0.230         0.40            4.20      0.035   
12              7.9             0.180         0.37            1.20      0.040   
13              6.6             0.160         0.40            1.50      0.044   
14              8.3             0.420         0.62           19.25      0.040   
15              6.6             0.170         0.38            1.50      0.032   
16              6.3             0.480         0.04            1.10      0.046   
17              6.2             0.660         0.48            1.20      0.029   
18              7.4             0.340         0.42            1.10      0.033   
19              6.5             0.310         0.14            7.50      0.044   
20              6.2             0.660         0.48            1.20      0.029   
21              6.4             0.310         0.38            2.90      0.038   
22              6.8             0.260         0.42            1.70      0.049   
23              7.6             0.670         0.14            1.50      0.074   
24              6.6             0.270         0.41            1.30      0.052   
25              7.0             0.250         0.32            9.00      0.046   
26              6.9             0.240         0.35            1.00      0.052   
27              7.0             0.280         0.39            8.70      0.051   
28              7.4             0.270         0.48            1.10      0.047   
29              7.2             0.320         0.36            2.00      0.033   
...             ...               ...          ...             ...        ...   
4868            5.8             0.230         0.31            4.50      0.046   
4869            6.6             0.240         0.33           10.10      0.032   
4870            6.1             0.320         0.28            6.60      0.021   
4871            5.0             0.200         0.40            1.90      0.015   
4872            6.0             0.420         0.41           12.40      0.032   
4873            5.7             0.210         0.32            1.60      0.030   
4874            5.6             0.200         0.36            2.50      0.048   
4875            7.4             0.220         0.26            1.20      0.035   
4876            6.2             0.380         0.42            2.50      0.038   
4877            5.9             0.540         0.00            0.80      0.032   
4878            6.2             0.530         0.02            0.90      0.035   
4879            6.6             0.340         0.40            8.10      0.046   
4880            6.6             0.340         0.40            8.10      0.046   
4881            5.0             0.235         0.27           11.75      0.030   
4882            5.5             0.320         0.13            1.30      0.037   
4883            4.9             0.470         0.17            1.90      0.035   
4884            6.5             0.330         0.38            8.30      0.048   
4885            6.6             0.340

### Variable explanation

1) Fixed Acidity :- It will show the level of fix acid in the winemaking process. It consist tartaric, malic, citric, and succinic acids.Fixed acidity will add sour indgredents in winemaking.

2) Volatile Acidity :- It will show the level of acetic acid in the winemaking process. Which consist acids like  lactic, formic, butyric, and propionic.Volatile acidity will add salty acids in winemaking.

3) Critic Acid:- It is component of fixed acidity.Which will sourness and crisp flavour to the wine.

4) Resdiual Sugar:- It refers to any natural grape sugars that are left over after fermentation ceases.

5) Chlorides:- It is component of volatile acidity.Which will add salty like vinegar during fermentation ceases.

6) Free Sulfer Dioxide:- It is level free sulfler dioxide which have add to maintain the propper molecular level.

7) Total sulfer Dioxide:- It is sum of free sulfer dioxide and total sulfer dioxide.

8) Ph:- pH describes how acidic or basic a wine is on a scale from 0 (very acidic) to 14 (very basic); most wines are between 3-3.4 on the pH scale

9) Sulphates :- Sulphates is a wine additive which can contribute to sulfur dioxide gas (S02) levels, which acts as an antimicrobial and antioxidant. 

## Performance of intial Exploratory Data Aanalysis

In [43]:
white.columns

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfer_dioxide', 'total_sulfer_dioxide', 'density',
       'pH', 'sulphates', 'alochol', 'Class'],
      dtype='object')

In [44]:
white.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
fixed_acidity           4898 non-null float64
volatile_acidity        4898 non-null float64
citric_acid             4898 non-null float64
residual_sugar          4898 non-null float64
chlorides               4898 non-null float64
free_sulfer_dioxide     4898 non-null float64
total_sulfer_dioxide    4898 non-null float64
density                 4898 non-null float64
pH                      4898 non-null float64
sulphates               4898 non-null float64
alochol                 4898 non-null float64
Class                   4898 non-null int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


### In the data there is no catagroical variables to study but we have all numerical variables


In [7]:
white.describe()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free_sulfer_dioxide  total_sulfer_dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alochol        Class  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     3.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     1.000000  
25%       3.090000     0.410000     9.500000     3.000000  
50%       3.180000     0.470000    10.400000     4.000000  
75%       3.280000     0.550000    11.400000     4.000000  
max       3.820000     1.080000    14.200000     7.000000

### Performing Normalisation

In [8]:
def normalize(white):
    result = white.copy()
    for feature_name in white.columns:
        max_value = white[feature_name].max()
        min_value = white[feature_name].min()
        result[feature_name] = (white[feature_name] - min_value) / (max_value - min_value)
    return result

In [9]:
wine=normalize(white)

In [12]:
wine.tail()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
4893       0.230769          0.127451     0.174699        0.015337   0.089021   
4894       0.269231          0.235294     0.216867        0.113497   0.112760   
4895       0.259615          0.156863     0.114458        0.009202   0.094955   
4896       0.163462          0.205882     0.180723        0.007669   0.038576   
4897       0.211538          0.127451     0.228916        0.003067   0.032641   

      free_sulfer_dioxide  total_sulfer_dioxide   density        pH  \
4893             0.076655              0.192575  0.077694  0.500000   
4894             0.191638              0.368910  0.150183  0.390909   
4895             0.097561              0.236659  0.104685  0.245455   
4896             0.062718              0.234339  0.030461  0.563636   
4897             0.069686              0.206497  0.044342  0.490909   

      sulphates   alochol     Class  
4893   0.325581  0.516129  0.500000  
4894   0.279070  0.258065  0.333333  
4895   0.279070  0.225806  0.500000  
4896   0.186047  0.774194  0.666667  
4897   0.116279  0.612903  0.500000

### Performance Classification

In [14]:
x = white.iloc[:,[0,1,2,3,4,5,6,7,8,9,10]].values
y = white.iloc[:,11].values

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [21]:
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

### Classifing the variables using Logistic Regression

In [22]:
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

C:\Users\Abhi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Abhi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [23]:
y_pred=classifier.predict(x_test)

In [31]:
y_pred

array([4, 3, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 3, 4, 4, 4, 3, 4, 4, 4, 4,
       4, 4, 4, 4, 3, 3, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       3, 4, 3, 4, 4, 4, 5, 4, 3, 4, 4, 4, 4, 4, 3, 4, 4, 3, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 3, 3, 4, 4, 4,
       4, 4, 4, 4, 4, 5, 3, 4, 3, 3, 4, 4, 5, 3, 4, 4, 3, 4, 4, 3, 4, 3,
       3, 4, 4, 4, 4, 5, 3, 3, 5, 4, 3, 4, 4, 3, 4, 5, 4, 4, 3, 4, 4, 4,
       4, 4, 4, 3, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 3, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 3, 4, 4, 4, 4, 3, 4,
       4, 4, 4, 4, 3, 4, 4, 4, 4, 3, 4, 4, 3, 5, 5, 4, 4, 4, 4, 4, 4, 5,
       4, 4, 4, 4, 3, 3, 4, 4, 4, 3, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 3, 4,
       4, 4, 3, 4, 3, 4, 5, 4, 4, 4, 3, 4, 4, 3, 4, 4, 4, 5, 4, 4, 4, 4,
       3, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 3, 4, 4, 3, 4, 4, 3, 3, 4, 4, 4,
       4, 4, 3, 4, 4, 4, 5, 4, 3, 3, 4, 3, 4, 4, 4,

### Neural Network model

In [33]:
from sklearn.neural_network import MLPClassifier

model = MLPClassifier(hidden_layer_sizes=(200,100), max_iter=1000)
model.fit(x, y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(200, 100), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [34]:
predicted_class=model.predict(x)

In [35]:
accuracy = accuracy_score(y.flatten(),predicted_class)

print(accuracy)

0.5179665169456921


## Confusion Matrix

In [37]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred)
print(cm)

[[  0   0   5   4   0   0]
 [  0   1  28  21   1   0]
 [  0   0 138 157   0   0]
 [  0   1  68 332   8   0]
 [  0   0  10 152  21   0]
 [  0   0   0  28   5   0]]


## Kinds of Nureal Network

In [38]:
nnmodel = MLPClassifier(hidden_layer_sizes=(30,50))

In [39]:
nnmodel.fit(x_train,y_train)

C:\Users\Abhi\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(30, 50), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [40]:
nnpredicted_class=nnmodel.predict(x_test)
accuracy_score(y_test,nnpredicted_class)

0.560204081632653

In [41]:
from sklearn.metrics import classification_report

report=classification_report(y_test,nnpredicted_class)
print(report)

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         9
           2       0.77      0.20      0.31        51
           3       0.63      0.58      0.61       295
           4       0.54      0.73      0.62       409
           5       0.50      0.38      0.43       183
           6       0.14      0.03      0.05        33

   micro avg       0.56      0.56      0.56       980
   macro avg       0.43      0.32      0.34       980
weighted avg       0.55      0.56      0.54       980



C:\Users\Abhi\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [42]:
nn_cm=confusion_matrix(y_test, nnpredicted_class)
print(nn_cm)

[[  0   1   4   4   0   0]
 [  0  10  23  18   0   0]
 [  0   2 172 116   5   0]
 [  0   0  63 297  46   3]
 [  0   0   9 102  69   3]
 [  0   0   0  15  17   1]]
